services:
  # 1. Backend-приложение (NestJS)
  backend:
    build:
      context: ./backend
    container_name: max-dobro-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  # 2. Frontend-приложение (React + Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: max-dobro-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  # 3. Чат-бот
  bot:
    build:
      context: ./chat-bot
    container_name: max-dobro-bot
    restart: always
    ports:
      - "10000:10000"
    env_file:
      - ./chat-bot/.env