services:
  - type: worker
    name: max-dobro-bot
    env: node
    plan: free
    rootDir: ./chat-bot
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_NAME
        sync: false